import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from "./redux/provider";

// Components
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'ffarfafasdsvfasgasdfgas',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
